apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: pahbrgrv8-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/pahbrgrv8-java-quarkus-gitops